name: Python CI with Poetry

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install -v

    - name: Download model weights
      run : |
        pip install gdown
        gdown 1xj44hXRfNeCyPgyaA1bsbleHJCuAFh82
        mv faster_rcnn_r50_fpn.pt chest_xray_detection/ml_detection_api/domain/models/faster_rcnn_r50_fpn.pt

    - name: Run tests
      run: |
        poetry run pytest tests